# pull official base image
FROM python:3.8.16

# enable venv
ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

COPY . ./Backend/
WORKDIR /Backend

# Upgrade packages
RUN apt update && apt install -y \
    libpq-dev python3-dev && rm -rf /var/lib/apt/lists/*

# install requirements
RUN pip install -r requirements.txt

EXPOSE 5050

# start flask gunicorn
ENTRYPOINT ["gunicorn", "-w 4","-b 0.0.0.0:5050", "main:app"]

